on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]


jobs:
  build:
    uses: kcduboiswiz/.github/.github/workflow-templates/wiz-docker.yml@main
    with:
      image_name: kcduboiswiz/big-python-api
      registry_url: docker.io
      image_tag: ${{ github.sha }}
    secrets: 
      wiz_client_id: ${{ secrets.WIZ_CLIENT_ID }}
      wiz_client_secret: ${{ secrets.WIZ_CLIENT_SECRET }}